using Microsoft.EntityFrameworkCore;
using UsersApi.Data.Entites;

namespace UsersApi.Data;

public class AppDbContext : DbContext
{
    public AppDbContext(DbContextOptions<AppDbContext> options)
        : base(options)
    {
    }

    public DbSet<User> Users { get; set; }
    
    protected override void OnModelCreating(ModelBuilder modelBuilder)
    {
        base.OnModelCreating(modelBuilder);

        // Configure User entity
        modelBuilder.Entity<User>(entity =>
        {
            // Set Id as the primary key
            entity.HasKey(e => e.Id);

            // Configure Id to be generated by the database
            entity.Property(e => e.Id).ValueGeneratedOnAdd();

            // Configure the rest of the fields as needed
            entity.Property(e => e.Email).IsRequired();
            entity.Property(e => e.Name).IsRequired();
            entity.Property(e => e.Phone).IsRequired();
        });
    }


}